-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.1
-- Generated: 2018-08-20 05:35 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.tech_hereford_bidresponses_1 (
    "schema_vendor"                               VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"                                 VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"                               VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"                              VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"                                     CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"                                 TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"                                    VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"                                    VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"                                  VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ext.debug.httpcalls.appnexus"                VARCHAR(5000) ENCODE ZSTD,
    "ext.debug.httpcalls.openx"                   VARCHAR(5000) ENCODE ZSTD,
    "ext.debug.resolvedrequest.at"                SMALLINT      ENCODE ZSTD,
    "ext.debug.resolvedrequest.device.ip"         VARCHAR(15)   ENCODE ZSTD,
    "ext.debug.resolvedrequest.device.ua"         VARCHAR(4096) ENCODE ZSTD,
    "ext.debug.resolvedrequest.ext.city"          VARCHAR(4096) ENCODE ZSTD,
    "ext.debug.resolvedrequest.ext.country"       VARCHAR(4096) ENCODE ZSTD,
    "ext.debug.resolvedrequest.id"                CHAR(36)      ENCODE ZSTD,
    "ext.debug.resolvedrequest.imp"               VARCHAR(5000) ENCODE ZSTD,
    "ext.debug.resolvedrequest.site.domain"       VARCHAR(4096) ENCODE ZSTD,
    "ext.debug.resolvedrequest.site.page"         VARCHAR(8192) ENCODE ZSTD,
    "ext.debug.resolvedrequest.site.publisher.id" VARCHAR(4096) ENCODE ZSTD,
    "ext.debug.resolvedrequest.source.tid"        CHAR(36)      ENCODE ZSTD,
    "ext.debug.resolvedrequest.test"              SMALLINT      ENCODE ZSTD,
    "ext.debug.resolvedrequest.tmax"              SMALLINT      ENCODE ZSTD,
    "ext.debug.resolvedrequest.user.id"           VARCHAR(4096) ENCODE ZSTD,
    "ext.responsetimemillis.appnexus"             SMALLINT      ENCODE ZSTD,
    "ext.responsetimemillis.openx"                SMALLINT      ENCODE ZSTD,
    "id"                                          CHAR(36)      ENCODE ZSTD,
    "page_name"                                   VARCHAR(4096) ENCODE ZSTD,
    "seatbid"                                     VARCHAR(5000) ENCODE ZSTD,
    "timestamp"                                   INT           ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.tech_hereford_bidresponses_1 IS 'iglu:tech.hereford/bidresponses/jsonschema/1-0-1';

ALTER TABLE atomic.tech_hereford_bidresponses_1 OWNER TO a_new_owner;
