-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.1
-- Generated: 2018-08-20 05:35 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.tech_hereford_httpreqs_2 (
    "schema_vendor"            VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"              VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"            VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"           VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"                  CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"              TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"                 VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"                 VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"               VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "at"                       SMALLINT      ENCODE ZSTD,
    "bday"                     VARCHAR(4096) ENCODE ZSTD,
    "device.ip"                VARCHAR(4096) ENCODE ZSTD,
    "device.ua"                VARCHAR(4096) ENCODE ZSTD,
    "ext.city"                 VARCHAR(255)  ENCODE ZSTD,
    "ext.country"              VARCHAR(255)  ENCODE ZSTD,
    "id"                       VARCHAR(4096) ENCODE ZSTD,
    "imp"                      VARCHAR(5000) ENCODE ZSTD,
    "page_name"                VARCHAR(255)  ENCODE ZSTD,
    "regs.ext.gdpr"            BIGINT        ENCODE ZSTD,
    "site.domain"              VARCHAR(4096) ENCODE ZSTD,
    "site.page"                VARCHAR(8192) ENCODE ZSTD,
    "site.publisher.id"        VARCHAR(255)  ENCODE ZSTD,
    "source.tid"               VARCHAR(4096) ENCODE ZSTD,
    "temp_ui_ds.adnxs.expires" VARCHAR(4096) ENCODE ZSTD,
    "temp_ui_ds.adnxs.uid"     VARCHAR(4096) ENCODE ZSTD,
    "temp_ui_ds.openx.expires" VARCHAR(4096) ENCODE ZSTD,
    "temp_ui_ds.openx.uid"     CHAR(36)      ENCODE ZSTD,
    "test"                     SMALLINT      ENCODE ZSTD,
    "timestamp"                INT           ENCODE ZSTD,
    "tmax"                     SMALLINT      ENCODE ZSTD,
    "user.ext.consent"         VARCHAR(256)  ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.tech_hereford_httpreqs_2 IS 'iglu:tech.hereford/httpreqs/jsonschema/2-0-1';

ALTER TABLE atomic.tech_hereford_httpreqs_2 OWNER TO a_new_owner;
