/*
 * Copyright (c) 2012-2016 Snowplow Analytics Ltd. All rights reserved.
 *
 * This program is licensed to you under the Apache License Version 2.0,
 * and you may not use this file except in compliance with the Apache License Version 2.0.
 * You may obtain a copy of the Apache License Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Apache License Version 2.0 is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Apache License Version 2.0 for the specific language governing permissions and limitations there under.
 */
package com.snowplowanalytics.iglu.schemaddl.redshift
package generators

// specs2
import org.specs2.Specification

import com.snowplowanalytics.iglu.schemaddl.sql._
import com.snowplowanalytics.iglu.schemaddl.sql.generators.DdlFile

class DdlFileSpec extends Specification { def is = s2"""
  Check DDL File specification
    render correct table definition $e1
  """

  def e1 = {
    val header = CommentBlock(Vector(
      "AUTO-GENERATED BY schema-ddl DO NOT EDIT",
      "Generator: schema-ddl 0.2.0",
      "Generated: 2016-03-31 15:52"
    ))
    val schemaCreate = CreateSchema("atomic")

    val createTable = CreateTable(
     "launch_missles_1",
      List(
        Column("status", SqlVarchar(64), Set(DistKey), Set(Nullability(NotNull))),
        Column("missionName", SqlVarchar(128), Set(), Set(Nullability(NotNull))),
        Column("geo_longitude", SqlDouble, Set(), Set()),
        Column("geo_latitude", SqlDouble, Set(), Set()),
        Column("rocket.model", SqlInteger, Set(), Set(Nullability(NotNull))),
        Column("rocket.series", SqlInteger, Set(), Set(Nullability(Null)))
      )
    )
    val commentOn = DdlGenerator.getTableComment(
      "launch_missles_1",
      Some("atomic"),
      "iglu:com.acme/event/jsonschema/1-2-1"
    )

    // no formatters
    val ddl = DdlFile(List(header, schemaCreate, createTable, commentOn)).render(Nil)

    // ordering happens in DdlGenerator.getTableDdl function
    ddl must beEqualTo(
      """|-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
         |-- Generator: schema-ddl 0.2.0
         |-- Generated: 2016-03-31 15:52
         |CREATE SCHEMA IF NOT EXISTS atomic;
         |CREATE TABLE IF NOT EXISTS launch_missles_1 (
         |    "status"        VARCHAR(64)      DISTKEY NOT NULL,
         |    "missionName"   VARCHAR(128)             NOT NULL,
         |    "geo_longitude" DOUBLE PRECISION,
         |    "geo_latitude"  DOUBLE PRECISION,
         |    "rocket.model"  INT                      NOT NULL,
         |    "rocket.series" INT                      NULL
         |);
         |COMMENT ON TABLE atomic.launch_missles_1 IS 'Source: iglu:com.acme/event/jsonschema/1-2-1';""".stripMargin)
  }
}
